# Multiple Linear Regression

In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv('/Users/deonschellito619/Desktop/Regression/Data/datasets_11262_15629_50_Startups.csv')

In [2]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
print(data.head())
data.shape

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


(50, 5)

In [4]:
data.corr()

R&D Spend  Administration  Marketing Spend    Profit
R&D Spend         1.000000        0.241955         0.724248  0.972900
Administration    0.241955        1.000000        -0.032154  0.200717
Marketing Spend   0.724248       -0.032154         1.000000  0.747766
Profit            0.972900        0.200717         0.747766  1.000000

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
data.iloc[:,[0,1,2]]=sc.fit_transform(data.iloc[:,[0,1,2]])
data.iloc[:,-1]=sc.fit_transform(data.iloc[:,-1].values.reshape(-1,1))


In [6]:
data.head()

R&D Spend  Administration  Marketing Spend       State    Profit
0   2.016411        0.560753         2.153943    New York  2.011203
1   1.955860        1.082807         1.923600  California  1.999430
2   1.754364       -0.728257         1.626528     Florida  1.980842
3   1.554784       -0.096365         1.422210    New York  1.776627
4   1.504937       -1.079919         1.281528     Florida  1.357740

In [7]:
x=data.iloc[:,[0,1,2]].values
y=data.iloc[:,-1]

In [8]:
#from sklearn.model_selection import  train_test_split
#x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x,y)
reg.score(x,y)

0.9507459940683246

In [9]:
reg.intercept_,reg.coef_

(-4.3781088542196174e-16, array([ 0.91757985, -0.01864043,  0.08261087]))

## Using Gradient Descent


In [10]:
xi=data.iloc[:,[0,1,2]].values
yi=data.iloc[:,-1].values

In [11]:
def gradientdescent(b0,b1,b2,b3,yi,xi,tolerance,eta,verbose=False):
    mag=100
    while mag>tolerance:
        coef=np.array([b0,b1,b2,b3])
        error=yi-(b0+(b1*xi[:,0])+(b2*xi[:,1])+(b3*xi[:,2]))
        derv=np.array([np.sum(error),np.sum(error*xi[:,0]),np.sum(error*xi[:,1]),np.sum(error*xi[:,2])])
        new_co=coef+((2*eta)*derv)
        if verbose==True:
            print(b0,b1,b2,b3)
        b0,b1,b2,b3=new_co[0],new_co[1],new_co[2],new_co[3]
        mag=np.sqrt(np.sum(error)**2+np.sum(error*xi[:,0])**2+np.sum(error*xi[:,1])**2+np.sum(error*xi[:,2])**2)
    return b0,b1,b2,b3


In [12]:
gradientdescent(0,0,0,0,yi,xi,0.01,0.001,verbose=True)

0 0 0 0
-5.1514348342607266e-17 0.09729004656594832 0.02007165682687214 0.07477657217414767
-9.592326932761354e-17 0.17894976493129816 0.03602259992136896 0.13509381182658636
-1.3411494137471893e-16 0.2476891052046175 0.04859659228854636 0.18351642611983943
-1.678657213233237e-16 0.3057432783101717 0.058405698496070566 0.22215877535577666
-1.9717560917342783e-16 0.35495603270642867 0.06595349304185381 0.2527638670969606
-2.1849189124623083e-16 0.3968483207595953 0.07165418695775432 0.276768494198963
-2.402522625288839e-16 0.4326749180917616 0.07584838977799803 0.29535694738960905
-2.6112445539183685e-16 0.46347110950161335 0.07881609808268926 0.3095053066254143
-2.7666757773658906e-16 0.4900911842352299 0.08078739801050575 0.3200179638564873
-2.9221070008134126e-16 0.5132401776224643 0.08195128354169848 0.3275577399148667
-3.0420110874729297e-16 0.5335000439766882 0.0824629217847171 0.33267071918613306
-3.135269821541443e-16 0.5513512377706855 0.08244963832022872 0.33580672860719357
-3

-4.356515148629116e-16 0.9109553679263586 -0.016307190986026107 0.08890856583548269
-4.3520742565306155e-16 0.9111052524569482 -0.016359982498716473 0.08876607503621353
-4.356515148629116e-16 0.9112517457223528 -0.016411579558107698 0.0886268082125553
-4.356515148629116e-16 0.9113949244528351 -0.016462009189758882 0.088490692419325
-4.3653969328261174e-16 0.9115348636425703 -0.01651129780774919 0.08835765636178539
-4.38316050122012e-16 0.9116716365889267 -0.016559471228513492 0.08822763035830226
-4.396483177515622e-16 0.9118053149308574 -0.016606554684364887 0.0881005463038468
-4.432010314303627e-16 0.9119359686864229 -0.016652572836711278 0.08797633763432358
-4.445332990599128e-16 0.912063666289466 -0.016697549788972834 0.0878549392917058
-4.45865566689463e-16 0.9121884746254552 -0.016741509099207193 0.08773628768995921
-4.45421477479613e-16 0.9123104590665184 -0.016784473792448965 0.08762032068173711
-4.467537451091631e-16 0.9124296835056838 -0.016826466372770025 0.08750697752582894


(-4.516387264175134e-16,
 0.9169806918042934,
 -0.018429397596705203,
 0.08318046822693904)

In [13]:
print('The b0 is {0} and b1 is {1} b2 is {2} b3 is {3}'.format(*gradientdescent(0,0,0,0,yi,xi,0.01,0.0001,verbose=False)))

The b0 is -4.524824959162236e-16 and b1 is 0.9169605771776391 b2 is -0.01842231293310023 b3 is 0.08319959060897653


In [14]:
reg.intercept_,reg.coef_

(-4.3781088542196174e-16, array([ 0.91757985, -0.01864043,  0.08261087]))

# Gradient Descent - General

In [15]:
def gradientdesc(*b,yi,xi,tolerane,eta,verbose=False):
    mag=100
    xi=np.c_[[1 for _ in range(len(xi))],xi]
    while mag>tolerane:
        coef=np.array([*b]).reshape(-1,1)
        pred=xi
        error=yi.reshape(-1,1)-pred.dot(coef)
        a=[np.sum(error)]
        for i in range(1,xi.shape[1]):
            a.append(np.sum(error*xi[:,i].reshape(-1,1)))
        derv=np.array(a)
        new_co=coef+((2*eta)*derv.reshape(-1,1))
        if verbose==True:
            print(*new_co)
        ns=new_co
        b=ns.flatten()
        m=[]
        for z in derv:
            m.append(z**2)
        mag=np.sqrt(np.sum(m))
    return b

In [16]:
gradientdescent(0,0,0,0,yi=yi,xi=xi,tolerance=0.01,eta=0.001)

(-4.516387264175134e-16,
 0.9169806918042934,
 -0.018429397596705203,
 0.08318046822693904)

# Coordinate Descent

In [57]:
xi=data.iloc[:,[0,1,2]].values
yi=data.iloc[:,-1].values

In [75]:
def coordinate_descent(X,y,alpha = .03, num_iters=20,normalize=False,verbose=False):
    if normalize==False:
        X=np.c_[np.ones(X.shape[0]),X]
        m,n = X.shape
        theta = np.zeros(n).reshape(-1,1)
        print(theta.flatten())
    
        for i in range(num_iters):
            for j in range(n):
                h = X @ theta 
                gradient =  (X[:,j] @ (h-y))
                theta[j] = theta[j] - alpha * gradient
                if verbose==True:
                    print(theta.flatten())
                       
        return theta 
    elif normalize==True:
        X=np.c_[np.ones(X.shape[0]),X]
        X = X / (np.linalg.norm(X,axis = 0)) 
        m,n = X.shape
        theta = np.zeros(n).reshape(-1,1)
        print(theta.flatten())
        for i in range(num_iters):
            for j in range(n):
                h = (X[:,0:j] @ theta[0:j]) + (X[:,j+1:] @ theta[j+1:])
                theta[j] =  (X[:,j] @ (y - h))
                if verbose==True:
                    print(theta.flatten())
                       
    return theta

In [72]:
coordinate_descent(xi,yi.reshape(-1,1),normalize=True)

array([[-3.08086889e-15],
       [ 6.48829263e+00],
       [-1.31814293e-01],
       [ 5.84129964e-01]])

In [76]:
coordinate_descent(xi,yi.reshape(-1,1),num_iters=100,normalize=False,verbose=True)

[0. 0. 0. 0.]
[-7.99360578e-16  0.00000000e+00  0.00000000e+00  0.00000000e+00]
[-7.99360578e-16  1.45935070e+00  0.00000000e+00  0.00000000e+00]
[-7.99360578e-16  1.45935070e+00 -2.28571481e-01  0.00000000e+00]
[-7.99360578e-16  1.45935070e+00 -2.28571481e-01 -4.74773634e-01]
[-3.53050922e-16  1.45935070e+00 -2.28571481e-01 -4.74773634e-01]
[-3.53050922e-16  1.32841233e+00 -2.28571481e-01 -4.74773634e-01]
[-3.53050922e-16  1.32841233e+00 -8.96626212e-02 -4.74773634e-01]
[-3.53050922e-16  1.32841233e+00 -8.96626212e-02 -8.84393259e-02]
[-4.92939023e-16  1.32841233e+00 -8.96626212e-02 -8.84393259e-02]
[-4.92939023e-16  9.23764071e-01 -8.96626212e-02 -8.84393259e-02]
[-4.92939023e-16  9.23764071e-01  6.37631918e-03 -8.84393259e-02]
[-4.92939023e-16  9.23764071e-01  6.37631918e-03  1.62624175e-01]
[-4.69624339e-16  9.23764071e-01  6.37631918e-03  1.62624175e-01]
[-4.69624339e-16  8.18484105e-01  6.37631918e-03  1.62624175e-01]
[-4.69624339e-16  8.18484105e-01  8.67540577e-03  1.62624175e-

[-4.36317649e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.36317649e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.36317649e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.36317649e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.36317649e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.36317649e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.42978987e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.42978987e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.42978987e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.42978987e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.29656311e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.29656311e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.29656311e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.29656311e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.62963001e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.629630

[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.09672296e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.03010958e-16  9.17579849e-01 -1.86404295e-02  8.26108670e-02]
[-4.030109

array([[-4.09672296e-16],
       [ 9.17579849e-01],
       [-1.86404295e-02],
       [ 8.26108670e-02]])